version: '3.9'

services:

  db:
    image: mysql
    container_name: mysql_db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_USER: user
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    networks:
      - msnetwork

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - "8090:8080"
    networks:
      - msnetwork

  portainer:
    image: portainer/portainer-ce:2.11.0
    container_name: portainer-io
    restart: always
    command: -H unix:///var/run/docker.sock
    ports:
      - "9000:9000"
    networks:
      - msnetwork
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  msnetwork:
    driver: bridge